package main

import (
	"dbgen/pkg/modelgen"
	"dbgen/pkg/schemas"
	"github.com/dave/jennifer/jen"
	"github.com/thorn-jmh/errorst"
)

func gen(schemaPath string) error {

	// first parse the schema
	jsch, err := schemas.FromJSONFile(schemaPath)
	if err != nil {
		return errorst.Wrap(err, "failed to parse schema file %s", schemaPath)
	}

	// then generate the code
	model, err := modelgen.GenerateModel(jsch)
	if err != nil {
		return err
	}

	// then write the code
	fp := jen.NewFile(packageName)
	fp.HeaderComment("Code generated by dbgen. DO NOT EDIT.")
	if err := model.Gen(fp); err != nil {
		return err
	}
	if err := fp.Save(outputDir + "/" + model.Name + ".go"); err != nil {
		return errorst.Wrap(err, "failed to save file")
	}
	return nil
}
